apiVersion: v1
kind: Service
metadata:
  name: nginx-web2-svc
  namespace: web2-namespace
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP